name: get-newest-version
on: 
#  push:
  schedule:
    - cron:  '30 3 * * 6'
  #手动编译
  workflow_dispatch:

jobs:
  build:
    name: get-newest-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pyquery
          python3 get-newest-version.py 0
          python3 get-newest-version.py 1
          python3 get-newest-version.py 2
          git config user.name "bot"
          git config user.email "bot@github.com"
          ls -al
          pwd
          cp /tmp/mainline.txt  txt/mainline.txt
          cp /tmp/mainlineurl.txt txt/mainlineurl.txt
          cp /tmp/stable.txt txt/stable.txt
          cp /tmp/stableurl.txt txt/stableurl.txt
          cp /tmp/longterm.txt txt/longterm.txt
          cp /tmp/longtermurl.txt txt/longtermurl.txt
          git pull
          git add txt/
          git commit -m "Create file with kernel version"
          git push || echo ""

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 7