name: Build kernel sdm845
on: 
#  push:
#    path:
#      - 'txt/*'
#  schedule:
#    - cron:  '30 5 * * 6'
  #手动编译
  workflow_dispatch:

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: install dep
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq gpg python3-pyquery wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev git lsb vim libelf-dev neofetch python3-pip python3-tk debhelper zstd dpkg-sig mmdebstrap qemu-user-static usrmerge binfmt-support systemd-container dwarves gcc-aarch64-linux-gnu

      - name: Build
        id: build
        run: bash build_mobian.sh

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.VERSION }}-mobian-sdm845
          files: ${{ github.workspace }}/artifact/*.*
          body: |
            这是 mobian-sdm845 内核！

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          keep_latest: 10
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 7